# Generated by Django 5.2.5 on 2025-09-21 22:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_alter_meal_options_meal_created_at_meal_updated_at_and_more'),
        ('orders', '0002_add_customer_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Order Item', 'verbose_name_plural': 'Order Items'},
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(blank=True, help_text='Customer email address (needed for payments and receipts).', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_identifier',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the customer, useful for anonymous or guest orders.', unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Customer name or table number. Optional for guest orders.', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('dine_in', 'Dine In'), ('take_out', 'Take-out')], default='dine_in', help_text='Type of order: Dine In or Take-out.', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the order.', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount for the order, calculated from OrderItems.', max_digits=8),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='meal',
            field=models.ForeignKey(help_text='The meal included in this order item.', on_delete=django.db.models.deletion.CASCADE, to='meals.meal'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(help_text='The order this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveBigIntegerField(default=1, help_text='Number of units of the meal in this order item.'),
        ),
    ]
