# Generated by Django 5.2.5 on 2025-09-22 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('dine_in', 'Dine In'), ('take_out', 'Take-out'), ('delivery', 'Delivery')], default='dine_in', help_text='Type of order: Dine In or Take-out.', max_length=10),
        ),
    ]
