# Generated by Django 5.2.5 on 2025-09-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Customer contact phone number.', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True, help_text='Delivery address for delivery orders.'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Delivery fee for delivery orders.', max_digits=6),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_instructions',
            field=models.TextField(blank=True, help_text='Special delivery instructions.'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_time',
            field=models.DateTimeField(blank=True, help_text='Preferred pickup time for takeaway/pickup orders.', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='table_number',
            field=models.CharField(blank=True, help_text='Table number for dine-in orders.', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('dine_in', 'Dine In'), ('takeaway', 'Takeaway'), ('delivery', 'Delivery'), ('pickup', 'Pickup')], default='dine_in', help_text='Type of order: Dine In, Takeaway, Delivery, or Pickup.', max_length=10),
        ),
    ]
