# Generated by Django 5.2.5 on 2025-10-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_tracking_code_order_user_orderitem_item_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('dine in', 'Dine In'), ('takeaway', 'Takeaway'), ('delivery', 'Delivery'), ('pickup', 'Pickup')], default='dine in', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment/Confirmation'), ('in progress', 'In Progress (Kitchen)'), ('ready', 'Ready for Handover'), ('delivered', 'Delivered'), ('completed', 'Completed/Closed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
