# Generated by Django 5.2.5 on 2025-09-21 17:13

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['name'], 'verbose_name': 'Meal', 'verbose_name_plural': 'Meals'},
        ),
        migrations.AddField(
            model_name='meal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True, help_text='Is the meal available for order?'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='prep_time',
            field=models.PositiveSmallIntegerField(help_text='Estimated Preparation time in minutes'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
