# Generated by Django 5.2.5 on 2025-09-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_alter_meal_options_meal_created_at_meal_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='is_veg',
            field=models.BooleanField(db_index=True, default=True, help_text='Is the meal vegetarian?'),
        ),
    ]
