# Generated by Django 5.2.5 on 2025-10-02 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_meal_is_veg'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='category',
            field=models.CharField(choices=[('main_course', 'Main Course'), ('desserts', 'Desserts'), ('drinks', 'Drinks'), ('appetizers', 'Appetizers'), ('sides', 'Sides')], db_index=True, default='main_course', max_length=20),
        ),
    ]
