# Generated by Django 5.2.7 on 2025-10-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meals", "0005_update_is_veg"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meal",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="meal",
            name="is_available",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="meal",
            name="is_veg",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="meal",
            name="prep_time",
            field=models.PositiveSmallIntegerField(
                help_text="Preparation time in minutes"
            ),
        ),
    ]
