# Generated by Django 5.2.5 on 2025-09-21 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('waiter', 'Waiter'), ('kitchen', 'Kitchen Staff'), ('admin', 'Administrator')], help_text='Select the role for the staff member', max_length=50, verbose_name='Staff Role'),
        ),
    ]
