# Generated by Django 5.2.5 on 2025-09-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bank_details',
            field=models.TextField(blank=True, help_text='Bank details for Mono payments.'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_token',
            field=models.CharField(blank=True, help_text='Payment token for Flutterwave or other payment processors.', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number for mobile money payments.', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider',
            field=models.CharField(blank=True, help_text='Mobile money provider (e.g., MTN, Vodafone).', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_ref',
            field=models.CharField(blank=True, help_text='Transaction reference for mobile money or bank transfers.', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('online', 'Online'), ('momo', 'Mobile Money'), ('mono', 'Mono')], default='cash', help_text='The method used for the payment.', max_length=10),
        ),
    ]
