# Generated by Django 5.2.5 on 2025-10-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_options_alter_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('online', 'Online'), ('momo', 'Mobile Money')], default='cash', help_text='The method used for the payment.', max_length=10),
        ),
    ]
